/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FabricsRouteImport } from './routes/fabrics'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentRouteImport } from './routes/apartment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PartnersIdRouteImport } from './routes/partners.$id'
import { Route as FabricsIdRouteImport } from './routes/fabrics.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSpecsRouteImport } from './routes/_authenticated/admin.specs'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminProductStatsRouteImport } from './routes/_authenticated/admin.product-stats'
import { Route as AuthenticatedAdminPartnerApplicationsRouteImport } from './routes/_authenticated/admin.partner-applications'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminHomeBlocksRouteImport } from './routes/_authenticated/admin.home-blocks'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/_authenticated/admin.forms'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminCustomerPhotosRouteImport } from './routes/_authenticated/admin.customer-photos'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminApartmentRouteImport } from './routes/_authenticated/admin.apartment'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as AuthenticatedAdminPartnersIndexRouteImport } from './routes/_authenticated/admin.partners.index'
import { Route as AuthenticatedAdminFabricsIndexRouteImport } from './routes/_authenticated/admin.fabrics.index'
import { Route as AuthenticatedAdminApartmentIndexRouteImport } from './routes/_authenticated/admin.apartment.index'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo.$'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as AuthenticatedAdminPartnersContentRouteImport } from './routes/_authenticated/admin.partners.content'
import { Route as AuthenticatedAdminPartnersCategoriesRouteImport } from './routes/_authenticated/admin.partners.categories'
import { Route as AuthenticatedAdminPartnersIdRouteImport } from './routes/_authenticated/admin.partners.$id'
import { Route as AuthenticatedAdminFabricsCategoriesRouteImport } from './routes/_authenticated/admin.fabrics.categories'
import { Route as AuthenticatedAdminFabricsIdRouteImport } from './routes/_authenticated/admin.fabrics.$id'
import { Route as AuthenticatedAdminApartmentDiscountsRouteImport } from './routes/_authenticated/admin.apartment.discounts'
import { Route as AuthenticatedAdminApartmentCategoriesRouteImport } from './routes/_authenticated/admin.apartment.categories'
import { Route as AuthenticatedAdminApartmentAnalyticsRouteImport } from './routes/_authenticated/admin.apartment.analytics'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricsRoute = FabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentRoute = ApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIdRoute = PartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnersRoute,
} as any)
const FabricsIdRoute = FabricsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FabricsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSpecsRoute = AuthenticatedAdminSpecsRouteImport.update({
  id: '/admin/specs',
  path: '/admin/specs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductStatsRoute =
  AuthenticatedAdminProductStatsRouteImport.update({
    id: '/admin/product-stats',
    path: '/admin/product-stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnerApplicationsRoute =
  AuthenticatedAdminPartnerApplicationsRouteImport.update({
    id: '/admin/partner-applications',
    path: '/admin/partner-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHomeBlocksRoute =
  AuthenticatedAdminHomeBlocksRouteImport.update({
    id: '/admin/home-blocks',
    path: '/admin/home-blocks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustomerPhotosRoute =
  AuthenticatedAdminCustomerPhotosRouteImport.update({
    id: '/admin/customer-photos',
    path: '/admin/customer-photos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApartmentRoute =
  AuthenticatedAdminApartmentRouteImport.update({
    id: '/admin/apartment',
    path: '/admin/apartment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPartnersIndexRoute =
  AuthenticatedAdminPartnersIndexRouteImport.update({
    id: '/admin/partners/',
    path: '/admin/partners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFabricsIndexRoute =
  AuthenticatedAdminFabricsIndexRouteImport.update({
    id: '/admin/fabrics/',
    path: '/admin/fabrics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApartmentIndexRoute =
  AuthenticatedAdminApartmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminApartmentRoute,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/admin/products/$id',
    path: '/admin/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersContentRoute =
  AuthenticatedAdminPartnersContentRouteImport.update({
    id: '/admin/partners/content',
    path: '/admin/partners/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersCategoriesRoute =
  AuthenticatedAdminPartnersCategoriesRouteImport.update({
    id: '/admin/partners/categories',
    path: '/admin/partners/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersIdRoute =
  AuthenticatedAdminPartnersIdRouteImport.update({
    id: '/admin/partners/$id',
    path: '/admin/partners/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFabricsCategoriesRoute =
  AuthenticatedAdminFabricsCategoriesRouteImport.update({
    id: '/admin/fabrics/categories',
    path: '/admin/fabrics/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFabricsIdRoute =
  AuthenticatedAdminFabricsIdRouteImport.update({
    id: '/admin/fabrics/$id',
    path: '/admin/fabrics/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApartmentDiscountsRoute =
  AuthenticatedAdminApartmentDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedAdminApartmentRoute,
  } as any)
const AuthenticatedAdminApartmentCategoriesRoute =
  AuthenticatedAdminApartmentCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminApartmentRoute,
  } as any)
const AuthenticatedAdminApartmentAnalyticsRoute =
  AuthenticatedAdminApartmentAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminApartmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apartment': typeof ApartmentRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/fabrics': typeof FabricsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/fabrics/$id': typeof FabricsIdRoute
  '/partners/$id': typeof PartnersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/apartment': typeof AuthenticatedAdminApartmentRouteWithChildren
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/customer-photos': typeof AuthenticatedAdminCustomerPhotosRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/home-blocks': typeof AuthenticatedAdminHomeBlocksRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/admin/product-stats': typeof AuthenticatedAdminProductStatsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/specs': typeof AuthenticatedAdminSpecsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/apartment/analytics': typeof AuthenticatedAdminApartmentAnalyticsRoute
  '/admin/apartment/categories': typeof AuthenticatedAdminApartmentCategoriesRoute
  '/admin/apartment/discounts': typeof AuthenticatedAdminApartmentDiscountsRoute
  '/admin/fabrics/$id': typeof AuthenticatedAdminFabricsIdRoute
  '/admin/fabrics/categories': typeof AuthenticatedAdminFabricsCategoriesRoute
  '/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/admin/partners/categories': typeof AuthenticatedAdminPartnersCategoriesRoute
  '/admin/partners/content': typeof AuthenticatedAdminPartnersContentRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/admin/apartment/': typeof AuthenticatedAdminApartmentIndexRoute
  '/admin/fabrics/': typeof AuthenticatedAdminFabricsIndexRoute
  '/admin/partners/': typeof AuthenticatedAdminPartnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apartment': typeof ApartmentRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/fabrics': typeof FabricsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/fabrics/$id': typeof FabricsIdRoute
  '/partners/$id': typeof PartnersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/customer-photos': typeof AuthenticatedAdminCustomerPhotosRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/home-blocks': typeof AuthenticatedAdminHomeBlocksRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/admin/product-stats': typeof AuthenticatedAdminProductStatsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/specs': typeof AuthenticatedAdminSpecsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/apartment/analytics': typeof AuthenticatedAdminApartmentAnalyticsRoute
  '/admin/apartment/categories': typeof AuthenticatedAdminApartmentCategoriesRoute
  '/admin/apartment/discounts': typeof AuthenticatedAdminApartmentDiscountsRoute
  '/admin/fabrics/$id': typeof AuthenticatedAdminFabricsIdRoute
  '/admin/fabrics/categories': typeof AuthenticatedAdminFabricsCategoriesRoute
  '/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/admin/partners/categories': typeof AuthenticatedAdminPartnersCategoriesRoute
  '/admin/partners/content': typeof AuthenticatedAdminPartnersContentRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/admin/apartment': typeof AuthenticatedAdminApartmentIndexRoute
  '/admin/fabrics': typeof AuthenticatedAdminFabricsIndexRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apartment': typeof ApartmentRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/fabrics': typeof FabricsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/fabrics/$id': typeof FabricsIdRoute
  '/partners/$id': typeof PartnersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/apartment': typeof AuthenticatedAdminApartmentRouteWithChildren
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/customer-photos': typeof AuthenticatedAdminCustomerPhotosRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/home-blocks': typeof AuthenticatedAdminHomeBlocksRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/_authenticated/admin/product-stats': typeof AuthenticatedAdminProductStatsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/specs': typeof AuthenticatedAdminSpecsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/apartment/analytics': typeof AuthenticatedAdminApartmentAnalyticsRoute
  '/_authenticated/admin/apartment/categories': typeof AuthenticatedAdminApartmentCategoriesRoute
  '/_authenticated/admin/apartment/discounts': typeof AuthenticatedAdminApartmentDiscountsRoute
  '/_authenticated/admin/fabrics/$id': typeof AuthenticatedAdminFabricsIdRoute
  '/_authenticated/admin/fabrics/categories': typeof AuthenticatedAdminFabricsCategoriesRoute
  '/_authenticated/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/_authenticated/admin/partners/categories': typeof AuthenticatedAdminPartnersCategoriesRoute
  '/_authenticated/admin/partners/content': typeof AuthenticatedAdminPartnersContentRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/_authenticated/admin/apartment/': typeof AuthenticatedAdminApartmentIndexRoute
  '/_authenticated/admin/fabrics/': typeof AuthenticatedAdminFabricsIndexRoute
  '/_authenticated/admin/partners/': typeof AuthenticatedAdminPartnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apartment'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/contacts'
    | '/delivery'
    | '/fabrics'
    | '/favorites'
    | '/partners'
    | '/promotions'
    | '/reviews'
    | '/fabrics/$id'
    | '/partners/$id'
    | '/product/$id'
    | '/admin/about'
    | '/admin/apartment'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/customer-photos'
    | '/admin/faqs'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/home-blocks'
    | '/admin/integrations'
    | '/admin/partner-applications'
    | '/admin/product-stats'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/specs'
    | '/admin/'
    | '/admin/apartment/analytics'
    | '/admin/apartment/categories'
    | '/admin/apartment/discounts'
    | '/admin/fabrics/$id'
    | '/admin/fabrics/categories'
    | '/admin/partners/$id'
    | '/admin/partners/categories'
    | '/admin/partners/content'
    | '/admin/products/$id'
    | '/api/public/photo/$'
    | '/admin/apartment/'
    | '/admin/fabrics/'
    | '/admin/partners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apartment'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/contacts'
    | '/delivery'
    | '/fabrics'
    | '/favorites'
    | '/partners'
    | '/promotions'
    | '/reviews'
    | '/fabrics/$id'
    | '/partners/$id'
    | '/product/$id'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/customer-photos'
    | '/admin/faqs'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/home-blocks'
    | '/admin/integrations'
    | '/admin/partner-applications'
    | '/admin/product-stats'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/specs'
    | '/admin'
    | '/admin/apartment/analytics'
    | '/admin/apartment/categories'
    | '/admin/apartment/discounts'
    | '/admin/fabrics/$id'
    | '/admin/fabrics/categories'
    | '/admin/partners/$id'
    | '/admin/partners/categories'
    | '/admin/partners/content'
    | '/admin/products/$id'
    | '/api/public/photo/$'
    | '/admin/apartment'
    | '/admin/fabrics'
    | '/admin/partners'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/apartment'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/contacts'
    | '/delivery'
    | '/fabrics'
    | '/favorites'
    | '/partners'
    | '/promotions'
    | '/reviews'
    | '/fabrics/$id'
    | '/partners/$id'
    | '/product/$id'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/apartment'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/customer-photos'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/forms'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/home-blocks'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/partner-applications'
    | '/_authenticated/admin/product-stats'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/specs'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/apartment/analytics'
    | '/_authenticated/admin/apartment/categories'
    | '/_authenticated/admin/apartment/discounts'
    | '/_authenticated/admin/fabrics/$id'
    | '/_authenticated/admin/fabrics/categories'
    | '/_authenticated/admin/partners/$id'
    | '/_authenticated/admin/partners/categories'
    | '/_authenticated/admin/partners/content'
    | '/_authenticated/admin/products/$id'
    | '/api/public/photo/$'
    | '/_authenticated/admin/apartment/'
    | '/_authenticated/admin/fabrics/'
    | '/_authenticated/admin/partners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApartmentRoute: typeof ApartmentRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  ContactsRoute: typeof ContactsRoute
  DeliveryRoute: typeof DeliveryRoute
  FabricsRoute: typeof FabricsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PromotionsRoute: typeof PromotionsRoute
  ReviewsRoute: typeof ReviewsRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrics': {
      id: '/fabrics'
      path: '/fabrics'
      fullPath: '/fabrics'
      preLoaderRoute: typeof FabricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartment': {
      id: '/apartment'
      path: '/apartment'
      fullPath: '/apartment'
      preLoaderRoute: typeof ApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$id': {
      id: '/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof PartnersIdRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/fabrics/$id': {
      id: '/fabrics/$id'
      path: '/$id'
      fullPath: '/fabrics/$id'
      preLoaderRoute: typeof FabricsIdRouteImport
      parentRoute: typeof FabricsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/specs': {
      id: '/_authenticated/admin/specs'
      path: '/admin/specs'
      fullPath: '/admin/specs'
      preLoaderRoute: typeof AuthenticatedAdminSpecsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/product-stats': {
      id: '/_authenticated/admin/product-stats'
      path: '/admin/product-stats'
      fullPath: '/admin/product-stats'
      preLoaderRoute: typeof AuthenticatedAdminProductStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partner-applications': {
      id: '/_authenticated/admin/partner-applications'
      path: '/admin/partner-applications'
      fullPath: '/admin/partner-applications'
      preLoaderRoute: typeof AuthenticatedAdminPartnerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/home-blocks': {
      id: '/_authenticated/admin/home-blocks'
      path: '/admin/home-blocks'
      fullPath: '/admin/home-blocks'
      preLoaderRoute: typeof AuthenticatedAdminHomeBlocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forms': {
      id: '/_authenticated/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customer-photos': {
      id: '/_authenticated/admin/customer-photos'
      path: '/admin/customer-photos'
      fullPath: '/admin/customer-photos'
      preLoaderRoute: typeof AuthenticatedAdminCustomerPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apartment': {
      id: '/_authenticated/admin/apartment'
      path: '/admin/apartment'
      fullPath: '/admin/apartment'
      preLoaderRoute: typeof AuthenticatedAdminApartmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners/': {
      id: '/_authenticated/admin/partners/'
      path: '/admin/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AuthenticatedAdminPartnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fabrics/': {
      id: '/_authenticated/admin/fabrics/'
      path: '/admin/fabrics'
      fullPath: '/admin/fabrics/'
      preLoaderRoute: typeof AuthenticatedAdminFabricsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apartment/': {
      id: '/_authenticated/admin/apartment/'
      path: '/'
      fullPath: '/admin/apartment/'
      preLoaderRoute: typeof AuthenticatedAdminApartmentIndexRouteImport
      parentRoute: typeof AuthenticatedAdminApartmentRoute
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners/content': {
      id: '/_authenticated/admin/partners/content'
      path: '/admin/partners/content'
      fullPath: '/admin/partners/content'
      preLoaderRoute: typeof AuthenticatedAdminPartnersContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners/categories': {
      id: '/_authenticated/admin/partners/categories'
      path: '/admin/partners/categories'
      fullPath: '/admin/partners/categories'
      preLoaderRoute: typeof AuthenticatedAdminPartnersCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners/$id': {
      id: '/_authenticated/admin/partners/$id'
      path: '/admin/partners/$id'
      fullPath: '/admin/partners/$id'
      preLoaderRoute: typeof AuthenticatedAdminPartnersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fabrics/categories': {
      id: '/_authenticated/admin/fabrics/categories'
      path: '/admin/fabrics/categories'
      fullPath: '/admin/fabrics/categories'
      preLoaderRoute: typeof AuthenticatedAdminFabricsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fabrics/$id': {
      id: '/_authenticated/admin/fabrics/$id'
      path: '/admin/fabrics/$id'
      fullPath: '/admin/fabrics/$id'
      preLoaderRoute: typeof AuthenticatedAdminFabricsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apartment/discounts': {
      id: '/_authenticated/admin/apartment/discounts'
      path: '/discounts'
      fullPath: '/admin/apartment/discounts'
      preLoaderRoute: typeof AuthenticatedAdminApartmentDiscountsRouteImport
      parentRoute: typeof AuthenticatedAdminApartmentRoute
    }
    '/_authenticated/admin/apartment/categories': {
      id: '/_authenticated/admin/apartment/categories'
      path: '/categories'
      fullPath: '/admin/apartment/categories'
      preLoaderRoute: typeof AuthenticatedAdminApartmentCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminApartmentRoute
    }
    '/_authenticated/admin/apartment/analytics': {
      id: '/_authenticated/admin/apartment/analytics'
      path: '/analytics'
      fullPath: '/admin/apartment/analytics'
      preLoaderRoute: typeof AuthenticatedAdminApartmentAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminApartmentRoute
    }
  }
}

interface AuthenticatedAdminApartmentRouteChildren {
  AuthenticatedAdminApartmentAnalyticsRoute: typeof AuthenticatedAdminApartmentAnalyticsRoute
  AuthenticatedAdminApartmentCategoriesRoute: typeof AuthenticatedAdminApartmentCategoriesRoute
  AuthenticatedAdminApartmentDiscountsRoute: typeof AuthenticatedAdminApartmentDiscountsRoute
  AuthenticatedAdminApartmentIndexRoute: typeof AuthenticatedAdminApartmentIndexRoute
}

const AuthenticatedAdminApartmentRouteChildren: AuthenticatedAdminApartmentRouteChildren =
  {
    AuthenticatedAdminApartmentAnalyticsRoute:
      AuthenticatedAdminApartmentAnalyticsRoute,
    AuthenticatedAdminApartmentCategoriesRoute:
      AuthenticatedAdminApartmentCategoriesRoute,
    AuthenticatedAdminApartmentDiscountsRoute:
      AuthenticatedAdminApartmentDiscountsRoute,
    AuthenticatedAdminApartmentIndexRoute:
      AuthenticatedAdminApartmentIndexRoute,
  }

const AuthenticatedAdminApartmentRouteWithChildren =
  AuthenticatedAdminApartmentRoute._addFileChildren(
    AuthenticatedAdminApartmentRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminApartmentRoute: typeof AuthenticatedAdminApartmentRouteWithChildren
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCustomerPhotosRoute: typeof AuthenticatedAdminCustomerPhotosRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHomeBlocksRoute: typeof AuthenticatedAdminHomeBlocksRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminPartnerApplicationsRoute: typeof AuthenticatedAdminPartnerApplicationsRoute
  AuthenticatedAdminProductStatsRoute: typeof AuthenticatedAdminProductStatsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSpecsRoute: typeof AuthenticatedAdminSpecsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminFabricsIdRoute: typeof AuthenticatedAdminFabricsIdRoute
  AuthenticatedAdminFabricsCategoriesRoute: typeof AuthenticatedAdminFabricsCategoriesRoute
  AuthenticatedAdminPartnersIdRoute: typeof AuthenticatedAdminPartnersIdRoute
  AuthenticatedAdminPartnersCategoriesRoute: typeof AuthenticatedAdminPartnersCategoriesRoute
  AuthenticatedAdminPartnersContentRoute: typeof AuthenticatedAdminPartnersContentRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminFabricsIndexRoute: typeof AuthenticatedAdminFabricsIndexRoute
  AuthenticatedAdminPartnersIndexRoute: typeof AuthenticatedAdminPartnersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminApartmentRoute:
    AuthenticatedAdminApartmentRouteWithChildren,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCustomerPhotosRoute: AuthenticatedAdminCustomerPhotosRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminHomeBlocksRoute: AuthenticatedAdminHomeBlocksRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminPartnerApplicationsRoute:
    AuthenticatedAdminPartnerApplicationsRoute,
  AuthenticatedAdminProductStatsRoute: AuthenticatedAdminProductStatsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSpecsRoute: AuthenticatedAdminSpecsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminFabricsIdRoute: AuthenticatedAdminFabricsIdRoute,
  AuthenticatedAdminFabricsCategoriesRoute:
    AuthenticatedAdminFabricsCategoriesRoute,
  AuthenticatedAdminPartnersIdRoute: AuthenticatedAdminPartnersIdRoute,
  AuthenticatedAdminPartnersCategoriesRoute:
    AuthenticatedAdminPartnersCategoriesRoute,
  AuthenticatedAdminPartnersContentRoute:
    AuthenticatedAdminPartnersContentRoute,
  AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  AuthenticatedAdminFabricsIndexRoute: AuthenticatedAdminFabricsIndexRoute,
  AuthenticatedAdminPartnersIndexRoute: AuthenticatedAdminPartnersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FabricsRouteChildren {
  FabricsIdRoute: typeof FabricsIdRoute
}

const FabricsRouteChildren: FabricsRouteChildren = {
  FabricsIdRoute: FabricsIdRoute,
}

const FabricsRouteWithChildren =
  FabricsRoute._addFileChildren(FabricsRouteChildren)

interface PartnersRouteChildren {
  PartnersIdRoute: typeof PartnersIdRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersIdRoute: PartnersIdRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApartmentRoute: ApartmentRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  ContactsRoute: ContactsRoute,
  DeliveryRoute: DeliveryRoute,
  FabricsRoute: FabricsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PromotionsRoute: PromotionsRoute,
  ReviewsRoute: ReviewsRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
